stages:
  - test
  - benchmark

test:
  stage: test
  script:
    - env
    - ifconfig
    - echo success > report.txt
    - echo key,value > report.csv
    - echo a,100 >> report.csv
    - echo b,200 >> report.csv
    - echo c,300 >> report.csv
  artifacts:
    paths:
      - report.txt

benchmark:
  stage: benchmark
  script:
    - echo success

