stages:
  - test
  - benchmark

test:
  stage: test
  script:
    - env
    - ifconfig
    - echo success > report.txt
  artifacts:
    paths:
      - report.txt

benchmark:
  stage: benchmark
  script:
    - echo success

